[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "samriddhi-backend"
version = "0.1.0"
dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "sqlmodel",
    "psycopg2-binary",
]

[tool.hatch.build.targets.wheel]
packages = ["app"]
